#!/bin/bash
#
# Create a core on disk
# arguments are: corename configdir

set -e

echo "Executing $0" "$@"

if [[ "${VERBOSE:-}" = "yes" ]]; then
    set -x
fi

CORE=${1:-gettingstarted}
CONFIG_SOURCE="${2:-}"
if [[ -z "$CONFIG_SOURCE" ]]; then
    DEFAULT_CONFIGS=(_default data_driven_schema_configs)
    for config_dir in "${DEFAULT_CONFIGS[@]}"; do
        config_dir="/opt/solr/server/solr/configsets/$config_dir"
        if [ -d "$config_dir" ]; then
           CONFIG_SOURCE="$config_dir"
           break
        fi
    done
    if [[ -z $CONFIG_SOURCE ]]; then
        echo "Cannot find default config"
        exit 1
    fi
fi

if [[ -z $SOLR_HOME ]]; then
    coresdir="/opt/solr/server/solr/mycores"
    mkdir -p $coresdir
else
    coresdir=$SOLR_HOME
fi
coredir="$coresdir/$CORE"
if [[ ! -d $coredir ]]; then
    cp -r "$CONFIG_SOURCE/" "$coredir"
    touch "$coredir/core.properties"
# 	 '<!-- <copyField source="*" dest="_text_"/> -->'
	sed -i 's/<!-- <copyField source="\*" dest="_text_"\/> -->/<copyField source="\*\" dest="_text_"\/\>/' "$coredir/conf/managed-schema"
    sed -i 's/<str name="pattern">\[^\\w-\\\.\]<\/str>/<str name="pattern">\[^\\w-\\\.\\]\\[]<\/str>/' "$coredir/conf/solrconfig.xml"

    echo created "$CORE"
else
    echo "core $CORE already exists"
fi