// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  test: false,
  version: env.npm_package_version,
  serverUrl: 'https://regtool.wlilab.eu/api/',
  defaultLanguage: 'en',
  supportedLanguages: ['ca', 'en', 'es'],
  eth: {
    httpUser: 'bloomen',
    httpPassword: '12345',
    ethRpcUrl: 'https://0x.bloomen.io/rpc/telsius/iccsclaimtruffle',
    ethBlockPollingTime: 4000,
    transactionStatusPollingTime: 1000,
    transactionCallDelayTime: 2000,
    hdMagicKey: 'xxXX_MAGIC_XXxx',
    contractConfig: {
      default: {
        value: 0,
        gasPrice: 0,
        gas: 9999999
      },
      networkId: '83584648538'
    }
  }
};
